# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-27 15:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='doj',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
