# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-21 13:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0005_person_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='photo',
            new_name='image',
        ),
    ]
