# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-21 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0006_auto_20171121_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(default=b'', upload_to=b'static/img'),
        ),
    ]
