# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-28 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0007_auto_20171121_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, choices=[(b'yellow', b'Yellow'), (b'red', b'Red'), (b'black', b'Black')], max_length=255, null=True)),
                ('size', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
            ],
        ),
    ]
