# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-28 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0008_bike'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
