# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-12 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0009_bike_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='detail',
            field=models.CharField(default=b'detail', max_length=30),
        ),
    ]
