# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-12 20:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def forwards_func(apps, schema_editor):
    person = apps.get_model("app2", "Person")
    detail = apps.get_model("app2", "detail")

    for item in person.objects.all():
        detail.objects.get_or_create(person=item, detail=item.detail)

class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0010_person_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(default=b'detail', max_length=30)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='det', to='app2.Person')),
            ],
        ),
         migrations.RunPython(forwards_func),
    ]
